# Generated by Django 3.0.3 on 2020-02-08 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aues_portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='institute', to='aues_portal.Institute', verbose_name='Институт'),
        ),
        migrations.AlterField(
            model_name='group',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='department', to='aues_portal.Department', verbose_name='Кафедра'),
        ),
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='groupid', to='aues_portal.Group', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='department', to='aues_portal.Department', verbose_name='Кафедра'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone',
            field=models.CharField(blank=True, max_length=12, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='post',
            field=models.CharField(blank=True, max_length=100, verbose_name='Занимаемая должность'),
        ),
    ]
