# Generated by Django 3.0.3 on 2020-02-08 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aues_portal', '0002_auto_20200208_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='adviser',
        ),
        migrations.AddField(
            model_name='student',
            name='adviser',
            field=models.ManyToManyField(blank=True, null=True, to='aues_portal.Teacher', verbose_name='Эдвайзер'),
        ),
    ]
