# Generated by Django 3.0.3 on 2020-02-08 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aues_portal', '0003_auto_20200208_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='adviser',
        ),
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='group', to='aues_portal.Group', verbose_name='Группа'),
        ),
    ]
