# Generated by Django 3.0.3 on 2020-02-08 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aues_portal', '0004_auto_20200208_1259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='group_adviser',
        ),
        migrations.AddField(
            model_name='group',
            name='group_adviser',
            field=models.ManyToManyField(to='aues_portal.Teacher', verbose_name='Эдвайзер группы'),
        ),
    ]
