# Generated by Django 3.0.3 on 2020-02-08 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aues_portal', '0005_auto_20200208_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='group_adviser',
        ),
        migrations.AddField(
            model_name='group',
            name='group_adviser',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_query_name='group_adviser', to='aues_portal.Teacher', verbose_name='Эдвайзер группы'),
            preserve_default=False,
        ),
    ]
