# Generated by Django 3.0.3 on 2020-02-08 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aues_portal', '0008_auto_20200208_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='doc_name',
        ),
        migrations.AlterField(
            model_name='documents',
            name='doc_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='document_name', to='aues_portal.Teacher', verbose_name='Кому принадлежит докумет'),
        ),
    ]
