# Generated by Django 3.0.3 on 2020-02-08 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aues_portal', '0009_auto_20200208_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='category',
            field=models.CharField(choices=[('document', '1'), ('sertificat', '2'), ('article', '3'), ('award', '4')], default=1, max_length=10, verbose_name='Год обучения'),
            preserve_default=False,
        ),
    ]
