# Generated by Django 3.0.3 on 2020-02-08 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aues_portal', '0010_documents_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('document', 'Документ(Дипломы)'), ('sertificat', 'Скан сертификатов(повышение квалификации)'), ('article', 'Оттиск из статьи'), ('award', 'Награды')], max_length=10, verbose_name='Категория')),
                ('file', models.FileField(upload_to='Teachers/Documents/', verbose_name='Документ')),
                ('doc_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='document_name', to='aues_portal.Teacher', verbose_name='Кому принадлежит докумет')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
        migrations.DeleteModel(
            name='Documents',
        ),
    ]
