# Generated by Django 3.0.3 on 2020-02-08 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aues_portal', '0011_auto_20200208_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='name',
            field=models.TextField(default=1, verbose_name='Описание документа'),
            preserve_default=False,
        ),
    ]
