# Generated by Django 3.0.3 on 2020-02-27 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aues_portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='info_en',
            field=models.TextField(blank=True, null=True, verbose_name='Информация о кафедре'),
        ),
        migrations.AddField(
            model_name='department',
            name='info_kk',
            field=models.TextField(blank=True, null=True, verbose_name='Информация о кафедре'),
        ),
        migrations.AddField(
            model_name='department',
            name='info_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Информация о кафедре'),
        ),
        migrations.AddField(
            model_name='department',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Полное название кафедры'),
        ),
        migrations.AddField(
            model_name='department',
            name='name_kk',
            field=models.CharField(max_length=100, null=True, verbose_name='Полное название кафедры'),
        ),
        migrations.AddField(
            model_name='department',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Полное название кафедры'),
        ),
        migrations.AddField(
            model_name='department',
            name='short_name_en',
            field=models.CharField(max_length=10, null=True, verbose_name='Аббревиатура кафедры'),
        ),
        migrations.AddField(
            model_name='department',
            name='short_name_kk',
            field=models.CharField(max_length=10, null=True, verbose_name='Аббревиатура кафедры'),
        ),
        migrations.AddField(
            model_name='department',
            name='short_name_ru',
            field=models.CharField(max_length=10, null=True, verbose_name='Аббревиатура кафедры'),
        ),
        migrations.AddField(
            model_name='document',
            name='name_en',
            field=models.TextField(null=True, verbose_name='Описание документа'),
        ),
        migrations.AddField(
            model_name='document',
            name='name_kk',
            field=models.TextField(null=True, verbose_name='Описание документа'),
        ),
        migrations.AddField(
            model_name='document',
            name='name_ru',
            field=models.TextField(null=True, verbose_name='Описание документа'),
        ),
        migrations.AddField(
            model_name='group',
            name='name_en',
            field=models.CharField(max_length=10, null=True, verbose_name='Название группы'),
        ),
        migrations.AddField(
            model_name='group',
            name='name_kk',
            field=models.CharField(max_length=10, null=True, verbose_name='Название группы'),
        ),
        migrations.AddField(
            model_name='group',
            name='name_ru',
            field=models.CharField(max_length=10, null=True, verbose_name='Название группы'),
        ),
        migrations.AddField(
            model_name='institute',
            name='info_en',
            field=models.TextField(blank=True, null=True, verbose_name='Информация об институте'),
        ),
        migrations.AddField(
            model_name='institute',
            name='info_kk',
            field=models.TextField(blank=True, null=True, verbose_name='Информация об институте'),
        ),
        migrations.AddField(
            model_name='institute',
            name='info_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Информация об институте'),
        ),
        migrations.AddField(
            model_name='institute',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Полное название института'),
        ),
        migrations.AddField(
            model_name='institute',
            name='name_kk',
            field=models.CharField(max_length=100, null=True, verbose_name='Полное название института'),
        ),
        migrations.AddField(
            model_name='institute',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Полное название института'),
        ),
        migrations.AddField(
            model_name='institute',
            name='short_name_en',
            field=models.CharField(max_length=10, null=True, verbose_name='Аббревиатура института'),
        ),
        migrations.AddField(
            model_name='institute',
            name='short_name_kk',
            field=models.CharField(max_length=10, null=True, verbose_name='Аббревиатура института'),
        ),
        migrations.AddField(
            model_name='institute',
            name='short_name_ru',
            field=models.CharField(max_length=10, null=True, verbose_name='Аббревиатура института'),
        ),
        migrations.AddField(
            model_name='student',
            name='name_en',
            field=models.CharField(max_length=20, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='student',
            name='name_kk',
            field=models.CharField(max_length=20, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='student',
            name='name_ru',
            field=models.CharField(max_length=20, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='student',
            name='patronymic_en',
            field=models.CharField(max_length=20, null=True, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='student',
            name='patronymic_kk',
            field=models.CharField(max_length=20, null=True, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='student',
            name='patronymic_ru',
            field=models.CharField(max_length=20, null=True, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='student',
            name='surname_en',
            field=models.CharField(max_length=20, null=True, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='student',
            name='surname_kk',
            field=models.CharField(max_length=20, null=True, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='student',
            name='surname_ru',
            field=models.CharField(max_length=20, null=True, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='education_en',
            field=models.TextField(blank=True, null=True, verbose_name='Образование'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='education_kk',
            field=models.TextField(blank=True, null=True, verbose_name='Образование'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='education_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Образование'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='name_en',
            field=models.CharField(max_length=20, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='name_kk',
            field=models.CharField(max_length=20, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='name_ru',
            field=models.CharField(max_length=20, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='patronymic_en',
            field=models.CharField(max_length=20, null=True, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='patronymic_kk',
            field=models.CharField(max_length=20, null=True, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='patronymic_ru',
            field=models.CharField(max_length=20, null=True, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='post_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Занимаемая должность'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='post_kk',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Занимаемая должность'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='post_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Занимаемая должность'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='qualification_up_en',
            field=models.TextField(blank=True, null=True, verbose_name='Повышение квалификации'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='qualification_up_kk',
            field=models.TextField(blank=True, null=True, verbose_name='Повышение квалификации'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='qualification_up_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Повышение квалификации'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='rezume_en',
            field=models.TextField(blank=True, null=True, verbose_name='Резюме'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='rezume_kk',
            field=models.TextField(blank=True, null=True, verbose_name='Резюме'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='rezume_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Резюме'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='science_articles_en',
            field=models.TextField(blank=True, null=True, verbose_name='Научные статьи'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='science_articles_kk',
            field=models.TextField(blank=True, null=True, verbose_name='Научные статьи'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='science_articles_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Научные статьи'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='surname_en',
            field=models.CharField(max_length=20, null=True, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='surname_kk',
            field=models.CharField(max_length=20, null=True, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='surname_ru',
            field=models.CharField(max_length=20, null=True, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='аwards_en',
            field=models.TextField(blank=True, null=True, verbose_name='Награды'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='аwards_kk',
            field=models.TextField(blank=True, null=True, verbose_name='Награды'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='аwards_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Награды'),
        ),
    ]
